### ISSUE TITLE
UnitInRaid usage

### ISSUE THREAD

**Issue by Road-block** [MrTreng/LootToChat#1]
https://github.com/MrTreng/LootToChat/blob/40171aac6ac5aee2bfe42f6f9e0bfa7fcc3aff28/LootToChat.lua#L34

You probably intended something like `UnitInRaid("player")` as a raid check, "unit" is not a valid unit token.

`GetNumGroupMembers()>0 and IsInRaid()` is an alternative raid check.

**Comment by MrTreng** [comment]
Absolutely right - thanks for spotting and reporting it :)
